name: dursley_wonka
instance:
  _target_: in_context_learning.nonergodic_state_sampler.NonergodicStateSampler
  process_names: [mr_name, mr_name]
  process_kwargs:
  - p: 0.4
    q: 0.25
  - p: 0.4
    q: 0.25
  process_weights: [ 0.5, 0.5 ]
