name: gru_rnn
instance:
  _target_: simplexity.predictive_models.gru_rnn.build_gru_rnn
  vocab_size: ${generative_process.vocab_size}
  num_layers: 4
  hidden_size: 64
  seed: ${seed}

load_checkpoint_name:
