name: gruformer
instance:
  _target_: simplexity.predictive_models.gruformer.build_llamalike_gruformer
  config:
    _target_: penzai.models.transformer.variants.llamalike_common.LlamalikeTransformerConfig
    num_kv_heads: 2
    query_head_multiplier: 2
    embedding_dim: 16
    projection_dim: 16
    mlp_hidden_dim: 16
    num_decoder_blocks: 2
    vocab_size: ${training_data_generator.vocab_size}
    mlp_variant: geglu_approx
    tie_embedder_and_logits: false
    rope_wavelength: 10000
    rms_norm_eps: 1e-06
    attention_type:
      _target_: penzai.models.transformer.variants.llamalike_common.AttentionTypeGlobalCausal
    use_post_attn_norm: false
    use_post_ffw_norm: false
    final_logit_softcap: null
    attn_logits_soft_cap: null
    query_scaling_factor: default
    parameter_dtype:
      _target_: jax.numpy.dtype
      _args_:
        - float32
    activation_dtype:
      _target_: jax.numpy.dtype
      _args_:
        - float32
    use_layer_stack: false
  init_base_rng:
    _target_: jax.random.PRNGKey
    seed: ${seed}
  name: gruformer

load_checkpoint_step:
