name: transformer
instance: 
  _target_: simplexity.predictive_models.transformer.build_transformer
  num_kv_heads: 2
  query_head_multiplier: 2
  embedding_dim: 16
  projection_dim: 16
  mlp_hidden_dim: 16
  num_decoder_blocks: 2
  vocab_size: 10
  mlp_variant: geglu_approx
  tie_embedder_and_logits: true
  attention_profile_horizon: 50





