"""Train a generative process vendored from generators, under `managed_run`.

This is the acceptance test for instantiating a process that lives in the consumer's project
rather than in simplexity: the process code under `tests/vendored_process/generators_copy/` is a
copy, not an import, and neither it nor its adapter references
`simplexity.generative_processes`.
"""

from pathlib import Path
from typing import Any

import jax
import jax.numpy as jnp
import pytest
import torch
from hydra import compose, initialize_config_dir
from omegaconf import DictConfig
from transformer_lens import HookedTransformer

import simplexity
from simplexity.generative_processes.torch_generator import generate_data_batch
from simplexity.run_management.protocols import GenerativeProcess, LogSpaceGenerativeProcess
from tests.vendored_process.adapter import VendoredGhmmProcess

CONFIG_DIR = str(Path(__file__).parent / "configs")
BATCH_SIZE = 4
SEQUENCE_LEN = 8
NUM_STEPS = 3


def _compose(tmp_path: Path) -> DictConfig:
    mlflow_uri = f"sqlite:///{(tmp_path / 'mlflow.db').absolute()}"
    overrides = [f"mlflow.tracking_uri={mlflow_uri}", f"mlflow.registry_uri={mlflow_uri}"]
    with initialize_config_dir(CONFIG_DIR, version_base="1.2"):
        return compose(config_name="test_vendored_process.yaml", overrides=overrides)


@simplexity.managed_run(strict=False, verbose=False)
def _train_on_vendored_process(cfg: DictConfig, components: simplexity.Components) -> dict[str, Any]:
    """Train the configured model on data generated by the vendored process."""
    generative_process = components.get_generative_process()
    assert generative_process is not None, "vendored process was not instantiated"

    predictive_model = components.get_predictive_model()
    assert isinstance(predictive_model, HookedTransformer)

    gen_states = jnp.repeat(generative_process.initial_state[None, :], BATCH_SIZE, axis=0)
    optimizer = torch.optim.Adam(predictive_model.parameters(), lr=0.01)
    loss_fn = torch.nn.CrossEntropyLoss()

    losses: list[float] = []
    inputs = torch.empty(0)
    for step in range(NUM_STEPS):
        gen_states, inputs, labels = generate_data_batch(
            gen_states,
            generative_process,
            BATCH_SIZE,
            SEQUENCE_LEN,
            jax.random.key(step),
            bos_token=cfg.generative_process.bos_token,
        )
        outputs = predictive_model(inputs)
        loss = loss_fn(outputs.reshape(-1, outputs.shape[-1]), labels.reshape(-1).long().to(outputs.device))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        losses.append(float(loss.detach().item()))

    return {
        "process": generative_process,
        "losses": losses,
        "inputs": inputs,
        "d_vocab": predictive_model.cfg.d_vocab,
        "resolved_vocab_size": cfg.generative_process.vocab_size,
        "resolved_base_vocab_size": cfg.generative_process.base_vocab_size,
        "resolved_bos_token": cfg.generative_process.bos_token,
    }


@pytest.fixture(scope="module")
def training_result(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Any]:
    """Run one managed training run against the vendored process."""
    tmp_path = tmp_path_factory.mktemp("vendored_process")
    return _train_on_vendored_process(_compose(tmp_path))  # pylint: disable=no-value-for-parameter


def test_vendored_process_is_instantiated(training_result: dict[str, Any]):
    """The vendored process is discovered and instantiated, not silently skipped."""
    assert isinstance(training_result["process"], VendoredGhmmProcess)


def test_vendored_process_is_not_a_simplexity_process(training_result: dict[str, Any]):
    """The process conforms structurally without inheriting from simplexity."""
    from simplexity.generative_processes.generative_process import (
        GenerativeProcess as GenerativeProcessBaseClass,
    )

    process = training_result["process"]
    assert not isinstance(process, GenerativeProcessBaseClass)
    assert isinstance(process, GenerativeProcess)


def test_vendored_process_lacks_log_space_operations(training_result: dict[str, Any]):
    """Log-space operations are an optional extension that generators does not provide."""
    assert not isinstance(training_result["process"], LogSpaceGenerativeProcess)


def test_vocabulary_fields_resolve_from_the_vendored_process(training_result: dict[str, Any]):
    """Vocabulary resolution reads the vendored process, so `d_vocab: ???` gets filled in."""
    assert training_result["resolved_base_vocab_size"] == 3
    assert training_result["resolved_bos_token"] == 3
    assert training_result["resolved_vocab_size"] == 4
    assert training_result["d_vocab"] == 4


def test_generated_tokens_are_in_vocabulary(training_result: dict[str, Any]):
    """Generated data has the expected shape and stays within the resolved vocabulary."""
    inputs = training_result["inputs"]
    assert inputs.shape == (BATCH_SIZE, SEQUENCE_LEN)
    assert int(inputs.min()) >= 0
    assert int(inputs.max()) < training_result["resolved_vocab_size"]


def test_training_steps_produce_finite_losses(training_result: dict[str, Any]):
    """Training runs end to end on vendored-process data."""
    losses = training_result["losses"]
    assert len(losses) == NUM_STEPS
    assert all(loss > 0 and loss == loss for loss in losses)
