defaults:
 - _self_
 - generative_process: mess3
 - predictive_model: gru_rnn
 - persistence: local_persister
 - logging: mlflow_logger
 - train: medium
 - override hydra/sweeper: optuna

seed: 0
experiment_name: ${predictive_model.name}_${generative_process.name}
run_name: ${now:%Y-%m-%d_%H-%M-%S}_${experiment_name}_${seed}

hydra:
  sweeper:
    direction: minimize
    n_trials: 20
    n_jobs: 1
    storage: null
    study_name: test
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      n_startup_trials: 10

    params:
      train.optimizer.instance.learning_rate: tag(log, interval(1e-4, 1e-1))
      train.batch_size: choice(16, 32, 64, 128)
      
      predictive_model.instance.hidden_size: int(interval(32, 256))
      predictive_model.instance.num_layers: int(interval(1, 4))
