defaults:
  - _self_
  - generative_process@training_data_generator: rpn_arithmetic
  - generative_process@validation_data_generator: rpn_arithmetic
  - predictive_model: pytorch_transformer
  - logging: mlflow_logger
  - training: small
  - evaluation@validation: small

seed: 0
experiment_name: pytorch_arithmetic_training
run_name: ${now:%Y-%m-%d_%H-%M-%S}_${experiment_name}_${seed}
