defaults:
 - _self_
 - state_sampler: dursley_wonka
 - generative_process@training_data_generator: dursley_wonka
 - generative_process@validation_data_generator: dursley_wonka
 - predictive_model: small_transformer
 - persistence: local_penzai_persister
 - logging: mlflow_logger
 - training: medium
 - evaluation@validation: small
 - override hydra/sweeper: optuna

seed: 0
experiment_name: ${predictive_model.name}_${training_data_generator.name}
run_name: ${now:%Y-%m-%d_%H-%M-%S}_${experiment_name}_${seed}
