defaults:
 - _self_
 - generative_process@training_data_generator: dursley_wonka
 - generative_process@validation_data_generator: dursley_wonka
 - state_sampler@training_state_sampler: dursley_wonka
 - state_sampler@validation_state_sampler: dursley_wonka
 - predictive_model: small_transformer
 - persistence: s3_persister
 - logging: mlflow_logger
 - training: medium
 - evaluation@validation: medium

seed: 0
experiment_name: ${predictive_model.name}_${training_data_generator.name}
run_name: ${now:%Y-%m-%d_%H-%M-%S}_${experiment_name}_${seed}
