# Main configuration for RLVR training experiments
defaults:
  - _self_
  - generative_process@training_data_generator: rpn_arithmetic
  - predictive_model: pytorch_transformer
  - logging: mlflow_logger
  - training@rlvr_training: rlvr_small

seed: 0
experiment_name: pytorch_arithmetic_rlvr
run_name: ${now:%Y-%m-%d_%H-%M-%S}_${experiment_name}_${seed}