defaults:
 - _self_
 - generative_process@training_data_generator: mess3_085
 - generative_process@validation_data_generator: mess3_085
 - predictive_model: transformer_lens_2L2H
 - persistence: s3_persister
 - logging: mlflow_logger
 - training: transformerlens
 - evaluation@validation: transformerlens

seed: 42
experiment_name: transformerlens_mess3
run_name: ${now:%Y-%m-%d_%H-%M-%S}_${experiment_name}_${seed}

