"""Visualization utilities, renderers, and structured config schemas."""

from .altair_renderer import build_altair_chart
from .data_registry import DataRegistry, DictDataRegistry, resolve_data_source
from .plotly_renderer import build_plotly_figure
from .structured_configs import (
    AestheticsConfig,
    AxisConfig,
    BackendType,
    ChannelAestheticsConfig,
    ChannelType,
    DataConfig,
    FacetConfig,
    GeometryConfig,
    GeometryType,
    GraphicsConfig,
    LabelConfig,
    LayerConfig,
    LegendConfig,
    PlotConfig,
    PlotLevelGuideConfig,
    PlotSizeConfig,
    ScaleConfig,
    SelectionConfig,
    SelectionType,
    TransformConfig,
    TransformOp,
)

__all__ = [
    "build_altair_chart",
    "build_plotly_figure",
    "DataRegistry",
    "DictDataRegistry",
    "resolve_data_source",
    "AestheticsConfig",
    "AxisConfig",
    "BackendType",
    "ChannelAestheticsConfig",
    "ChannelType",
    "DataConfig",
    "FacetConfig",
    "GeometryConfig",
    "GeometryType",
    "GraphicsConfig",
    "LabelConfig",
    "LayerConfig",
    "LegendConfig",
    "PlotConfig",
    "PlotLevelGuideConfig",
    "PlotSizeConfig",
    "ScaleConfig",
    "SelectionConfig",
    "SelectionType",
    "TransformConfig",
    "TransformOp",
]
