# RLVR training configuration - small scale
defaults:
  - _self_

# Basic training parameters
seed: ${seed}
num_epochs: 10
samples_per_epoch: 1000
max_prompt_length: 25
max_generation_length: 50
complexity_range: [1, 3]

# PPO-specific parameters
ppo_steps: 100
learning_rate: 1.0e-5
batch_size: 8
mini_batch_size: 4
gradient_accumulation_steps: 1
ppo_epochs: 4
cliprange: 0.2
cliprange_value: 0.2
vf_coef: 0.1
target_kl: 0.1
early_stopping: false

# Generation parameters
temperature: 0.7
top_p: 0.9

# Reward parameters
reward_type: "combined"
boxed_weight: 0.3
correct_weight: 0.7

# Logging and checkpointing
log_every: 1
checkpoint_every: null
max_batches_per_epoch: 10