version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
    stream: ext://sys.stdout

loggers:
  databricks.sdk:
    level: WARNING
    handlers: []
    propagate: true
  simplexity:
    level: WARNING
    handlers: []
    propagate: true
  absl:
    level: WARNING
    handlers: []
    propagate: true
  boto3:
    level: WARNING
    handlers: []
    propagate: true
  botocore:
    level: WARNING
    handlers: []
    propagate: true
  chex:
    level: WARNING
    handlers: []
    propagate: true
  dotenv:
    level: WARNING
    handlers: []
    propagate: true
  equinox:
    level: WARNING
    handlers: []
    propagate: true
  hydra:
    level: WARNING
    handlers: []
    propagate: true
  hydra_optuna_sweeper:
    level: WARNING
    handlers: []
    propagate: true
  hydra_plugins:
    level: WARNING
    handlers: []
    propagate: true
  jax:
    level: WARNING
    handlers: []
    propagate: true
  jax._src:
    level: WARNING
    handlers: []
    propagate: true
  jaxlib:
    level: WARNING
    handlers: []
    propagate: true
  jaxtyping:
    level: WARNING
    handlers: []
    propagate: true
  jupyter:
    level: WARNING
    handlers: []
    propagate: true
  matplotlib:
    level: WARNING
    handlers: []
    propagate: true
  mlflow:
    level: WARNING
    handlers: []
    propagate: true
  nbqa:
    level: WARNING
    handlers: []
    propagate: true
  optax:
    level: WARNING
    handlers: []
    propagate: true
  orbax:
    level: WARNING
    handlers: []
    propagate: true
  pandas:
    level: WARNING
    handlers: []
    propagate: true
  penzai:
    level: WARNING
    handlers: []
    propagate: true
  plotly:
    level: WARNING
    handlers: []
    propagate: true
  pytest:
    level: WARNING
    handlers: []
    propagate: true
  pytest_cov:
    level: WARNING
    handlers: []
    propagate: true
  pyright:
    level: WARNING
    handlers: []
    propagate: true
  ruff:
    level: WARNING
    handlers: []
    propagate: true
  torch:
    level: WARNING
    handlers: []
    propagate: true
  transformer_lens:
    level: WARNING
    handlers: []
    propagate: true
  treescope:
    level: WARNING
    handlers: []
    propagate: true
  datasets:
    level: WARNING
    handlers: []
    propagate: true

root:
  level: WARNING
  handlers:
    - console
